apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-ram-min-max-test
#  namespace: test
spec:
  limits:
  - default:
      cpu: 100m
      memory: 200Mi
    defaultRequest:
      cpu: 40m
      memory: 100Mi
    max:
      cpu: "200m"
      memory: 256Mi
    min:
      cpu: "10m"
      memory: 90Mi
    type: Container
