# pod-for-specific-node-selector.yml
#
apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: learning
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          memory: "500Mi"
        requests:
          memory: "300Mi"
  nodeSelector:
        sku: small 

#
# First label one/more nodes with some kind of tag
# we are classifying our nodes as small, medium &
# heavy and the label name is "sku" value can be
# "small / medium / heavy"
#
# First label nodeone.example.com as small:
#
# kubectl label nodes nodeone.example.com sku=small
#
# Confirm for the labels on nodes using:
#
# kubectl get nodes --show-labels 
#
# create namespace learning -
# kubectl create namespace learning
#
# run the pod
# kubectl create -f pod-for-specific-node-selector.yml
#
# check the pod
# kubectl get pods --namespace=learning --output=wide
#
# get details about pod
# kubectl describe pod/nnappone --namespace=learning
#
# check for the node where its running
# 
# Also look for: 
# Node-Selectors:  sku=small 
#
# value in the kubectl describe output
#
# delete pod
# kubectl delete pod/nnappone --namespace=learning
#
# delete the label from nodeone.example.com
# kubectl label node nodeone.example.com sku-
#
