# pod-with-cpu-exceed.yml

apiVersion: v1
kind: Pod
metadata:
  name: nnappone
  namespace: learning
  labels:
   app: nnappone
spec:
  containers:
    - name: networknuts-app
      image: lovelearnlinux/webserver:v1
      resources:
        limits:
          cpu: "4"
        requests:
          cpu: "4"


#
# the pod wants 4 cpu's which is not available
# on any node in the cluster. So it should fail
# with "insufficient cpu" message.
#
# create namespace learning -
# kubectl create namespace learning
#
# run the pod
# kubectl create -f pod-with-cpu-exceed.yml
#
# check the pod
# kubectl get pods
#
# get details about pod
# kubectl describe pod/nnappone --namespace=learning
#
# delete pod
# kubectl delete pod/nnappone --namespace=learning
#
