apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-both
  labels:
    name: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #### MANDATORY
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disk
                operator: In
                values:
                - ssd
      #### SOFT RULES
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 80
              preference:
                matchExpressions:
                - key: memory
                  operator: In
                  values:
                  - medium
            - weight: 20
              preference:
                matchExpressions:
                - key: cpu
                  operator: In
                  values:
                  - i7
                  - i5
      containers:
      - name: boxone
        image: docker.io/lovelearnlinux/webserver:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 70m
            memory: 64Mi
